<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>JarvisLauncher</RootNamespace>
    <AssemblyName>JarvisLauncher</AssemblyName>
    <!-- Shrink binary by requiring .NET 8 Runtime to be installed on PC -->
    <SelfContained>false</SelfContained>
    <PublishSelfContained>false</PublishSelfContained>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Management" Version="10.0.11" />
    <PackageReference Include="System.Speech" Version="10.0.11" />
    <PackageReference Include="Vosk" Version="0.3.38" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

</Project>
