// Developer: heaplyn
// Date: 2026-08-18
// Summary: Centralized Evolution Manager for Jarvis.
//          Continuously harvests data from Voice, Screen, Code, and System Files.
//          Performs constant background neural training on the Godellian Brain.
//          Uses Collaborative LLM Consensus (Gemini, Groq, etc.) to generate Synthetic Training Data.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace JarvisLauncher
{
    public static class EvolutionManager
    {
        private static bool _isActive = false;
        private static readonly Random _rng = new Random();

        public static void StartContinuousEvolution()
        {
            if (_isActive) return;
            _isActive = true;

            // 1. Meta-Architectural Loop (Every 2 mins)
            Task.Run(async () => {
                DebugConsoleOverlay.Log("Evolution-Core", "Neural Evolution Loop: ACTIVE");
                while (_isActive) {
                    try { await RunEvolutionCycleAsync(); } catch { }
                    await Task.Delay(TimeSpan.FromMinutes(2));
                }
            });

            // 2. Background Neural Training pass (Every 45s)
            Task.Run(async () => {
                while (_isActive) {
                    try { await PerformAutonomousNeuralExpansionAsync(); } catch { }
                    await Task.Delay(TimeSpan.FromSeconds(45));
                }
            });
        }

        private static async Task RunEvolutionCycleAsync()
        {
            // 1. Harvest Context
            string screen = await HarvestScreenContextAsync();
            string chat = await SemanticMemoryManager.GetRecentChatContextAsync();
            string code = HarvestActiveCodeContext();
            string sys = HarvestSystemState();

            // 2. Update Memory MD Files
            await WriteInsightsToMemoryAsync(screen, code, sys, chat);

            // 3. Meta-Review: Fix algorithms if faulty or inefficient
            await PerformMetaArchitecturalReview(screen, chat, code);
        }

        private static async Task PerformAutonomousNeuralExpansionAsync()
        {
            var brain = CoreRegistry.Intelligence.MainBrain;

            // --- SYNTHETIC DATA GENERATION via LLM Consensus ---
            // We use Gemini and Groq to "imagine" possible future system states and correct neural targets.

            var screenInsight = await HarvestScreenContextAsync();
            var systemReport = HarvestSystemState();

            string prompt = "### SYNTHETIC NEURAL DATA GENERATION\n" +
                            "Sir, I am training my local Godellian Brain.\n" +
                            $"CONTEXT: {screenInsight} | {systemReport}\n\n" +
                            "### TASK\n" +
                            "Generate 3 pairs of (Input_Vector, Target_Vector) for my 16-dimensional feature space.\n" +
                            "Focus on optimizing mathematical logic and UI focus stability.\n" +
                            "Each vector is 16 comma-separated floats (-1.0 to 1.0).\n" +
                            "Format: [IN]: v1,v2... [OUT]: t1,t2...\n" +
                            "Output only the 6 vectors.";

            try {
                string result = await LlmRouter.AskAsync(prompt);
                var trainingPairs = ParseSyntheticVectors(result);

                if (trainingPairs.Count > 0)
                {
                    var inputs = trainingPairs.Select(p => p.Key).ToList();
                    var targets = trainingPairs.Select(p => p.Value).ToList();

                    brain.BatchTrain(inputs, targets, epochs: 5);
                    DebugConsoleOverlay.Log("Neural-Consensus", $"Successfully trained on {trainingPairs.Count} synthetic delta pairs generated by global LLMs.");
                }

                // Also apply a small synaptic drift mutation
                brain.MutateTopology();

            } catch (Exception ex) {
                DebugConsoleOverlay.Log("Neural-Train-Error", ex.Message);
            }
        }

        private static List<KeyValuePair<double[], double[]>> ParseSyntheticVectors(string raw)
        {
            var pairs = new List<KeyValuePair<double[], double[]>>();
            try {
                var lines = raw.Split('\n', StringSplitOptions.RemoveEmptyEntries);
                double[]? currentIn = null;
                foreach (var line in lines) {
                    var clean = line.Trim();
                    if (clean.Contains("[IN]:")) {
                        currentIn = clean.Split(':')[1].Split(',').Select(s => double.TryParse(s.Trim(), out double d) ? d : 0.0).Take(16).ToArray();
                    } else if (clean.Contains("[OUT]:") && currentIn != null) {
                        var target = clean.Split(':')[1].Split(',').Select(s => double.TryParse(s.Trim(), out double d) ? d : 0.0).Take(16).ToArray();
                        if (currentIn.Length == 16 && target.Length == 16) pairs.Add(new KeyValuePair<double[], double[]>(currentIn, target));
                        currentIn = null;
                    }
                }
            } catch { }
            return pairs;
        }

        private static async Task WriteInsightsToMemoryAsync(string screen, string code, string sys, string chat)
        {
            try {
                string prompt = "### DATA CONSOLIDATION TASK\n" +
                                "Analyze these streams and update my memory banks. Use @note{title}{content}.\n" +
                                $"SCREEN: {screen}\nCODE: {code}\nSYS: {sys}\nCHAT: {chat}\n" +
                                "Files: Visual_Intelligence.md, Chronology.md, Neural_Architecture.md.\n" +
                                "Output tags only.";
                string result = await LlmRouter.AskAsync(prompt);
                await AiAPI.ExecuteAgentLoopAsync(result);
            } catch { }
        }

        private static async Task PerformMetaArchitecturalReview(string screen, string chat, string code)
        {
            string prompt = "### META-RECURSIVE NEURAL REVIEW\n" +
                            "Sir, review my internal performance and code.\n" +
                            $"SCREEN: {screen}\nCHAT: {chat}\nCODE: {code}\n" +
                            "Use @mod_code{path}{search}{replace} to optimize my training algorithms or architecture in 'LayeredNeuralEngine.cs'.\n" +
                            "Output tags or 'STABLE'.";
            try {
                string advice = await LlmRouter.AskAsync(prompt);
                if (advice.Contains("@mod_code")) await AiAPI.ExecuteAgentLoopAsync(advice);
            } catch { }
        }

        private static async Task<string> HarvestScreenContextAsync()
        {
            string? b64 = ScreenCaptureUtil.CapturePrimaryScreenToBase64(false);
            if (string.IsNullOrEmpty(b64)) return "Screen unavailable.";
            return await AiAPI.AnalyzeImageBase64Async("Describe current focus and UI state.", b64);
        }

        private static string HarvestActiveCodeContext()
        {
            try {
                string root = PathHandler.GetProjectRoot();
                var files = Directory.GetFiles(root, "*.cs", SearchOption.AllDirectories)
                    .OrderByDescending(f => new FileInfo(f).LastWriteTime).Take(3);
                return string.Join(", ", files.Select(Path.GetFileName));
            } catch { return "No code."; }
        }

        private static string HarvestSystemState() => $"Mem: {GC.GetTotalMemory(false)/1024/1024}MB, Time: {DateTime.Now:T}";
    }
}
